Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 4/12/2023
Var
largura, comprimento: real
resultado: real

Inicio
// entrada
Escreval ("Informe a largura: ")
Leia (largura)

Escreval ("Informe o comprimento: ")
Leia (comprimento)

// processamento
resultado <- largura * comprimento

// saida
Escreval ("Área quadrada = ", resultado)

Fimalgoritmo