Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 4/12/2023
Var
valor_euros: real
valor_reais: real

Inicio
// entrada
Escreval ("Informe o valor em Euros: ")
Leia (valor_euros)

// processamento
valor_reais <- valor_euros * 5.52

// saida
Escreval ("Valor em Reais: R$ ", valor_reais)


Fimalgoritmo