Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 4/12/2023
Var
nota1, nota2, nota3: real
media: real

Inicio
// entrada
Escreval ("Informe N1: ")
leia (nota1)

Escreval ("Informe N2: ")
Leia (nota2)

Escreval ("Informe N3: ")
Leia (nota3)

// processamento
media <- (nota1 + nota2 + nota3) / 3

// saida
Escreval ("Média do aluno: ", media)

Fimalgoritmo