Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 4/14/2023
Var
litros_abastecidos: real
km_litro: real
autonomia: real

Inicio
Escreva ("Quantida de litros abastecida: ")
Leia (litros_abastecidos)

Escreva ("Km que o veículo faz por litro: ")
Leia (km_litro)

autonomia <- litros_abastecidos * km_litro

Escreval ("Autonomia é de: ", autonomia)

Fimalgoritmo