Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 4/14/2023
Var
x, y: inteiro

Inicio
Escreva ("Informe idade 1: ")
Leia (x)

Escreva ("Informe idade 2: ")
Leia (y)

Se (x > y) então
   Escreval ("Pessoa 1 é mais velha.")
Senão
   Escreval ("Pessoa 2 é mais velha ou tem mesma idade")
FimSe



Fimalgoritmo