Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 4/10/2023
Var
// Seção de Declarações das variáveis 
idade1: inteiro
idade2: inteiro
nome1, nome2: caractere

Inicio
// entrada
nome1 <- "Fulano"
nome2 <- "Beltrano"
idade1 <- 23
idade2 <- 32

// saida
Escreval (nome1, " tem ", idade1, " anos")
Escreval (nome2, " tem ", idade2, " anos")


Fimalgoritmo